"""Operational reporting against NAMIS, driven by plain-language requests."""

from .authoring import QueryDraft, draft_query, narrate
from .catalog import NamisCatalog, TableSpec, get_catalog, load_catalog
from .cron import CronError, describe, is_due, next_run, parse
from .datasource import (
    DataSourceError,
    NamisSource,
    QueryResult,
    TableInfo,
    close_source,
    get_source,
    render_schema_catalogue,
)
from .import_saved import ImportedReport, import_directory, parse_saved_report
from .render import (
    PDF_MAX_COLUMNS,
    SUPPORTED_FORMATS,
    Artifact,
    to_xlsx,
    write_artifacts,
)
from .runner import execute, run_due
from .service import (
    ReportError,
    approve_definition,
    can_access,
    create_definition,
    due_definitions,
    fingerprint,
    get_definition,
    get_run,
    is_approved,
    list_definitions,
    list_runs,
    prune_runs,
    require_access,
    set_schedule,
    update_definition,
)
from .sqlguard import GuardResult, UnsafeQuery, validate
from .structured import (
    FieldRef,
    FilterSpec,
    JoinCondition,
    JoinSpec,
    ReportSpecError,
    SortSpec,
    StructuredReport,
    compile_report,
)

__all__ = [
    "PDF_MAX_COLUMNS",
    "SUPPORTED_FORMATS",
    "Artifact",
    "CronError",
    "DataSourceError",
    "GuardResult",
    "NamisSource",
    "QueryDraft",
    "QueryResult",
    "ReportError",
    "TableInfo",
    "UnsafeQuery",
    "approve_definition",
    "can_access",
    "close_source",
    "create_definition",
    "describe",
    "draft_query",
    "due_definitions",
    "execute",
    "fingerprint",
    "get_definition",
    "get_run",
    "get_source",
    "is_approved",
    "is_due",
    "list_definitions",
    "list_runs",
    "narrate",
    "next_run",
    "parse",
    "prune_runs",
    "render_schema_catalogue",
    "require_access",
    "run_due",
    "set_schedule",
    "update_definition",
    "validate",
    "FieldRef",
    "FilterSpec",
    "ImportedReport",
    "JoinCondition",
    "JoinSpec",
    "NamisCatalog",
    "ReportSpecError",
    "SortSpec",
    "StructuredReport",
    "TableSpec",
    "compile_report",
    "get_catalog",
    "import_directory",
    "load_catalog",
    "parse_saved_report",
    "to_xlsx",
    "write_artifacts",
]
